# Generated by Django 5.2.4 on 2025-07-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='number',
            field=models.PositiveIntegerField(editable=False, unique=True),
        ),
    ]
