# Generated by Django 5.2.4 on 2025-07-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0002_alter_student_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='room',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Room 1'), (2, 'Room 2'), (3, 'Room 3'), (4, 'Room 4'), (5, 'Room 5')], null=True),
        ),
    ]
