# Generated by Django 5.2.4 on 2025-07-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0003_student_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue', models.TextField(default='[]')),
                ('index', models.IntegerField(default=0)),
            ],
        ),
    ]
