# Generated by Django 5.2.4 on 2025-07-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0004_roomqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('in_exam', 'In Exam'), ('on_waiting_list', 'On Waiting List')], default='waiting', max_length=20),
        ),
    ]
