# Generated by Django 5.2.4 on 2025-07-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0005_student_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_count', models.PositiveIntegerField(default=5)),
            ],
        ),
    ]
