# Generated by Django 5.2.4 on 2025-07-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0006_screensettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='screensettings',
            name='waiting_count',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='screensettings',
            name='room_count',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('waiting', 'ينتظر'), ('in_exam', 'في السبر'), ('on_waiting_list', 'في قائمة الانتظار')], default='waiting', max_length=20),
        ),
    ]
