# Generated by Django 5.2.4 on 2025-07-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0008_remove_student_id_student_birth_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('final_grade', models.IntegerField()),
                ('result', models.CharField(max_length=50)),
                ('room', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='exam_type',
            field=models.CharField(blank=True, choices=[('gh', 'غيباً'), ('nz', 'نظراً')], max_length=10, null=True, verbose_name='غيباً/نظراً'),
        ),
    ]
