# Generated by Django 5.2.4 on 2025-07-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0009_gradedstudent_alter_student_exam_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('grade', models.IntegerField()),
                ('result', models.CharField(max_length=50)),
                ('room', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
