# Generated by Django 5.2.4 on 2025-07-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0010_examresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GradedStudent',
        ),
        migrations.AddField(
            model_name='screensettings',
            name='estimate_time_per_student',
            field=models.IntegerField(default=5, verbose_name='مدة التقدير بالدقائق لكل طالب'),
        ),
    ]
