# Generated by Django 5.2.4 on 2025-07-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0011_delete_gradedstudent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screensettings',
            name='estimate_time_per_student',
            field=models.IntegerField(default=5),
        ),
    ]
