# Generated by Django 5.2.4 on 2025-07-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0012_alter_screensettings_estimate_time_per_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('waiting', 'ينتظر'), ('on_waiting_list', 'قائمة الانتظار'), ('in_exam', 'في السبر '), ('finished', 'أنهى')], default='waiting', max_length=20),
        ),
    ]
