# Generated by Django 5.2.4 on 2025-07-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0014_alter_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('waiting', 'ينتظر'), ('in_exam', 'في السبر'), ('on_waiting_list', 'قائمة الانتظار'), ('finished', 'تم الانتهاء')], default='waiting', max_length=20),
        ),
    ]
