# Generated by Django 5.2.4 on 2025-07-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0015_alter_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mistakes_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
