# Generated by Django 5.2.4 on 2025-07-24 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0016_student_grade_student_mistakes_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='screensettings',
            name='exam_start_time',
            field=models.TimeField(default='07:00'),
        ),
    ]
