# Generated by Django 5.2.4 on 2025-07-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0017_screensettings_exam_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
