# Generated by Django 5.2.4 on 2025-07-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0018_student_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='sub_room',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
