# Generated by Django 5.2.4 on 2025-07-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0019_examresult_sub_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subroom',
            field=models.IntegerField(default=1),
        ),
    ]
